### get profiilikuva
GET http://localhost:3000/api/v1/users/avatar/60

### post profiilikuva
POST http://localhost:3000/api/v1/users/avatar/60
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="kuva_nimi"

Profiilikuva
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="kuva"; filename="profiilikuva.jpg"
Content-Type: image/jpeg

< kuvat/profiilikuva.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### delete
DELETE http://localhost:3000/api/v1/users/avatar/1

### put
PUT http://localhost:3000/api/v1/users/avatar/60
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="kuva"; filename="profiilikuva2.jpg"
Content-Type: image/jpeg

< kuvat/profiilikuva2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### get by id
GET http://localhost:3000/api/v1/users/avatar/4