### 
GET http://localhost:3000/api/v1/kayttaja

### uusi rekisteröityminen
POST http://localhost:3000/api/v1/kayttaja 
Content-Type: application/json

{
"name": "Sara", "lastname": "Pappila", "username": "sarapapp", "password": "12345", "email": "sarapap@metropolia.fi", "phone": "0445423713"
}

### uusi kirjautuminen
POST http://localhost:3000/api/v1/kayttaja/login
Content-Type: application/json

{
"username": "sarapap2", "password": "12345"
}

### 
GET http://localhost:3000/api/v1/kayttaja/info/58

### update user password 
PUT http://localhost:3000/api/v1/kayttaja/password/6
Content-Type: application/json

{
"salasana": "123456"
}

### update user info 
PUT http://localhost:3000/api/v1/kayttaja/info/56
Content-Type: application/json

{
"etunimi": "Sarppa", "sukunimi": "Pappila", "tunnus": "kolmas", "email": "sara@metropolia.fi", "puhelin": "1234567"
}

