### kaikki käyttäjät
GET http://localhost:3000/api/v1/users

### uusi rekisteröityminen
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
"name": "Sara", "lastname": "Pappila", "username": "sarapap3", "password": "12345", "email": "sarapap@metropolia.fi", "phone": "0445423713"
}

### uusi kirjautuminen
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
"username": "sarapap2", "password": "12345"
}

### get user info
GET http://localhost:3000/api/v1/users/info/58

### update user password 
PUT http://localhost:3000/api/v1/users/password/6
Content-Type: application/json

{
"salasana": "123456"
}

### update user info 
PUT http://localhost:3000/api/v1/users/info/56
Content-Type: application/json

{
"etunimi": "Sarppa", "sukunimi": "Pappila", "tunnus": "kolmas", "email": "sara@metropolia.fi", "puhelin": "1234567"
}

### get profiilikuva
GET http://localhost:3000/api/v1/users/avatar/60

### put profiilikuva
PUT http://localhost:3000/api/v1/users/avatar/60
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="kuva"; filename="profiilikuva2.jpg"
Content-Type: image/jpeg

< kuvat/profiilikuva2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

